// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXfe4bs-qpA41-nW6FOG5OPG0wBlyNYqg',
    appId: '1:436323539302:web:bbb92a61d3828f692bd0a7',
    messagingSenderId: '436323539302',
    projectId: 'hyeongfile',
    authDomain: 'hyeongfile.firebaseapp.com',
    storageBucket: 'hyeongfile.appspot.com',
    measurementId: 'G-XZ4NBV9KKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAqdx4ikPGdoohfNF2or7QqxbkSUvaigs',
    appId: '1:436323539302:android:dc9ba33bd82fa3a02bd0a7',
    messagingSenderId: '436323539302',
    projectId: 'hyeongfile',
    storageBucket: 'hyeongfile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQVcNBzU4DxS0pSunxAvoOFq9xx5zUKrc',
    appId: '1:436323539302:ios:9a70a132d24958302bd0a7',
    messagingSenderId: '436323539302',
    projectId: 'hyeongfile',
    storageBucket: 'hyeongfile.appspot.com',
    iosClientId: '436323539302-e3b5b0fpmrnab6qi3jecjcolbfqjhbor.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiTranslator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQVcNBzU4DxS0pSunxAvoOFq9xx5zUKrc',
    appId: '1:436323539302:ios:61bb839562f93bb52bd0a7',
    messagingSenderId: '436323539302',
    projectId: 'hyeongfile',
    storageBucket: 'hyeongfile.appspot.com',
    iosClientId: '436323539302-dojaeiltb6ktmjhr319o9hhtbacpf0q4.apps.googleusercontent.com',
    iosBundleId: 'com.example.apiTranslator.RunnerTests',
  );
}
